- name: ngnix instal and run
  hosts: frontend
  tasks:
  - name: install ngnix server
    ansible.builtin.package:
     name: ngnix
     state: present


  - name: start ngnix
    ansible.builtin.service:
     name: ngnix
     state: started
     enabled: yes
