- name: play level variables
  hosts: local
  connection: local
  vars:
   COURSE: ansible
   DURATION: 10HR
   TRAINER: rajkumar

  tasks:
  - name: print course information
    ansible.builtin.debug:
     msg: "hello {{ COURSE }}, course duration {{ DURATION }}, trainer is {{ TRAINER }}"