- name: ansible datatypes
  hosts: local
  connection: local
  vars:
   DURATION: 120 
   COURSE: devops with aws
   IS_LIVE: true
   TOOLS: 
   - linux
   - shell
   - ansible
   CONCEPTS:
      CI: jenkins
      SCRIPTING: "shell, ansible, terraform, python"
  tasks:
  - name: print cousre info
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }}, tools are: {{ TOOLS }}, concepts are: {{ CONCEPTS }}"
