[frontend]
172.31.27.219

[frontend:vars]
ansible_user=ec2-user 
ansible_password=DevOps321



[backend]
172.31.27.219


[database]
172.31.27.219



[local]
localhost

[local:vars]
COURSE=ansible
DURATION=12hr
TRAINER=Rajkumar