- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: instal mongodb
    anisble.builtin.dnf:
      name: mongodb-org
      state: present
      